include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_constructors_over_static_methods: false
    always_put_required_named_parameters_first: true
    prefer_double_quotes: false
    #public_member_api_docs: true
    lines_longer_than_80_chars: true
    avoid_print: false