name: flutter_on_the_go
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  lint: ^1.0.0
  redux: ^4.0.0
  reselect: ^0.4.0
  redux_thunk: ^0.3.0
  flutter_redux: ^0.6.0
  dio: ^3.0.8
  kiwi: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true